### ISSUE TITLE
(a -> b -> c) -> b -> (a -> c) doesn't find flip

### ISSUE THREAD

**Issue by ghost** [klaftertief/elm-search#1]
http://package.elm-lang.org/packages/elm-lang/core/4.0.1/Basics#flip

**Comment by klaftertief** [comment]
Thanks for the report. The search works by comparing the parsed type annotations from the docs with the one from the input. And it's strict/dumb with parens. I'll have a look how to make it smarter in this regard.

`Basics.flip` is annotated as `(a -> b -> c) -> b -> a -> c` which works as a query.

**Comment by klaftertief** [comment]
Should be better now. Can you confirm that it's working?

**Comment by ghost** [comment]
Works! Nice.
