### ISSUE TITLE
Wanted functions

### ISSUE THREAD

**Issue by ghost** [klaftertief/elm-search#13]
I searched `Int -> String` because I wanted `toRoman` (Roman numeral). There's no `toRoman` today, but if I could log that I wanted it, and others could too, then someone in the mood for writing algorithms, e.g. a competition, could know which functions are most in demand, then submit them to Elm Search, perhaps notifying me that `toRoman` is ready.

**Comment by klaftertief** [comment]
Hm, I think there are better places for such community related and interactive features. And the search is client-side only (and I expect it to be like that for the foreseeable future). I could set up the analytics to track searches (it only tracks visits) to be able to provide some data like that manually...

**Comment by ghost** [comment]
My thinking here was that as you'd have entered the Int -> String search once on Elm Search, it'd be nice not to have to do that again (e.g. on another site) to request the function. Perhaps Elm Search could just export the search to another site, e.g. in the URL? I guess that other site should be built first!

Even if the searches were tracked and e.g. found a lot of Int -> String searches, I'd need to know if the results had satisfied the searcher or not, right?
