### ISSUE TITLE
Doesn't find aliases with flipped parameters

### ISSUE THREAD

**Issue by ghost** [klaftertief/elm-search#2]
E.g. `List a -> Int -> a` finds `!!` ("Alias for getAt, but with the parameters flipped."), but not getAt (found by flipping the parameters to `Int -> List a -> a`). Had the authors not made an alias, I'd have to think to flip the parameters myself.

http://klaftertief.github.io/elm-search/?q=List%20a%20-%3E%20Int%20-%3E%20a

**Comment by klaftertief** [comment]
Sorry, I don't understand the issue.

A search for [`List a -> Int -> a`](http://klaftertief.github.io/elm-search/?q=List%20a%20-%3E%20Int%20-%3E%20a) finds `!!`, and a search for its correct annotation [`List a -> Int -> Maybe a`](http://klaftertief.github.io/elm-search/?q=List%20a%20-%3E%20Int%20-%3E%20Maybe%20a) pushes the result to the top.

A search for the flipped version [`Int -> List a -> a`](http://klaftertief.github.io/elm-search/?q=Int%20-%3E%20List%20a%20-%3E%20a) also finds `getAt`, but a bit further down. And the search for the correct annotation [`Int -> List a -> Maybe a`](http://klaftertief.github.io/elm-search/?q=Int%20-%3E%20List%20a%20-%3E%20Maybe%20a) finds it as the first result.

So did you expect to expect values with e.g. `Int -> List a -> List a` or `Int -> Array a -> a` to appear below `Int -> List a -> Maybe a` when searching for `Int -> List a -> a`?

**Comment by ghost** [comment]
`List a -> Int -> a` _doesn't_ find `getAt`. getAt is only mentioned by chance in `!!`'s description.

**Comment by klaftertief** [comment]
I see. The search is strict with the position of function arguments. They are compared pairwise in order. I'll have a look at comparing more/all combinations of arguments, but this will probably a bit expensive.

**Comment by ghost** [comment]
Hoogle does it, but I can't see how: https://github.com/ndmitchell/hoogle
http://hoogle.haskell.org/?hoogle=List%20a%20-%3E%20Int%20-%3E%20a
http://hoogle.haskell.org/?hoogle=Int%20-%3E%20List%20a%20-%3E%20a

**Comment by klaftertief** [comment]
I've published a new version with a more relaxed search for both the order of a list of types (here parameters in a function) and the comparison of a `a` with e.g. a `Maybe a`.

So a search for `List a -> Int -> a` now finds both `getAt` and the flipped infix `!!`.

**Comment by klaftertief** [comment]
I forgot to mention that the search might be a bit slower. Can you confirm that it's working and not too slow?

**Comment by ghost** [comment]
Speed is fine (I didn't notice any slowness). `List a -> Int -> a` found `!!` and `getAt`. When I then searched for `Int -> List a -> a`, I wasn't sure if it had worked, probably because the results are the same. I'll open this as another issue.
