### ISSUE TITLE
Update for elm 0.19 packages

### ISSUE THREAD

**Issue by andys8** [klaftertief/elm-search#28]
I assume the search needs to be updated because `elm-lang` packages exist instead of `elm` and e.g. `elm-test` is referencing `elm-community` and not `elm-explorations`.

https://github.com/klaftertief/elm-search/blob/ef6bb10e7230c01d04c3c968f7c056fb898b1721/src/scripts/Setup.elm#L41

This endpoint won't be available anymore.

**Comment by klaftertief** [comment]
That’s for the report. I’ll be updating elm-search in early November.

**Comment by klaftertief** [comment]
The new version is available at https://klaftertief.github.io/elm-search/.
