### ISSUE TITLE
No confirmation that a search has worked other than the results

### ISSUE THREAD

**Issue by ghost** [klaftertief/elm-search#3]
This is only a problem if you search for two different things that have the same results, e.g. `List a -> Int -> a` and `Int -> List a -> a`, because you don't know, when you search for the second thing, whether it's worked or not, because the results look the same. Suggest titling the results with the search.

**Comment by klaftertief** [comment]
Yes, the UX is not really where I want it to be. E.g. there is no indication of empty results neither. This is one of the main reasons why I haven't made any public announcements.
