### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by miniBill** [klaftertief/elm-search#44]
Could you please update this?

**Comment by klaftertief** [comment]
Thanks for reporting. I need to port CI to a new provider.
I _wanted_ to do this with additional changes a while ago, but could not bite what I planned to cook.

**Comment by miniBill** [comment]
Thanks for you work :)
I understand how maintaining OSS projects is a thankless job, and I appreciate what you've done so far.

I hope you'll find time to update it, but I understand that it can take an unpredictable amount of time

**Comment by lydell** [comment]
GitHub Actions is really nice.

Here’s how to do a Node.js based setup (with optional caching): https://github.com/actions/setup-node (search for “basic”)

Here’s an example of how to deploy to GitHub Pages with it: https://github.com/actions/starter-workflows/blob/main/pages/static.yml

Don’t know if it helps, but here’s how I do it in one of my own projects (not any Elm there though, but I don’t think it matters much): https://github.com/lydell/LinkHints/blob/main/.github/workflows/ci.yml

**Comment by klaftertief** [comment]
Thanks for the links and the nudge.
A new deploy is now online, and CI is set up to deploy each day.

**Comment by miniBill** [comment]
Thank you, that's awesome :purple_heart:
